import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class WordSuggestionService {
  words: string[] = [
    // ===== Gemüse =====
    'Kartoffel',
    'Süßkartoffel',
    'Karotte',
    'Möhre',
    'Zwiebel',
    'Knoblauch',
    'Tomate',
    'Cherrytomate',
    'Gurke',
    'Paprika',
    'rote Paprika',
    'gelbe Paprika',
    'grüne Paprika',
    'Zucchini',
    'Aubergine',
    'Spinat',
    'Blattspinat',
    'Kopfsalat',
    'Eisbergsalat',
    'Römersalat',
    'Brokkoli',
    'Blumenkohl',
    'Weißkohl',
    'Rotkohl',
    'Grünkohl',
    'Lauch',
    'Porree',
    'Sellerie',
    'Stangensellerie',
    'Knollensellerie',
    'Radieschen',
    'Rettich',
    'Rote Bete',
    'Kürbis',
    'Hokkaido Kürbis',
    'Butternut Kürbis',
    'Mais',
    'Erbsen',
    'grüne Erbsen',
    'Zuckerschoten',
    'grüne Bohnen',
    'Wachsbohnen',
    'Pilze',
    'Champignons',
    'Pfifferlinge',
    'Steinpilze',
    'Shiitake',
    'Austernpilze',
    'Fenchel',
    'Spargel',
    'weißer Spargel',
    'grüner Spargel',
    'Artischocke',
    'Okra',
    'Mangold',
    'Pak Choi',
    'Chinakohl',
    'Frühlingszwiebel',
    'Schalotte',
    'Ingwer',
    'Chili',
    'grüne Chili',
    'rote Chili',
    'Knoblauchzehe',
    'Zwiebelgrün',
    'Rucola',
    'Feldsalat',
    'Endivie',
    'Chicorée',
    'Topinambur',
    'Pastinake',
    'Steckrübe',
    'Kohlrabi',
    'Brokkoli Röschen',
    'Blumenkohl Röschen',
    'Salatherz',
    'Lauchzwiebel',
    'Palmkohl',
    'Kresse',
    'Alfalfa Sprossen',
    'Sojasprossen',
    'Bambussprossen',
    'Meerrettich',
    'Wasabi',
    'Wirsing',
    'Mairübe',
    'Schwarzwurzel',
    'Zuckererbsen',
    'Romanesco',
    'Rosenkohl',
    'Speiserübe',
    'Mangoldstiele',
    'Zwiebel rot',
    'Perlzwiebel',
    'Süßkartoffel Pommes',
    'Gemüsemais',
    'Baby Spinat',
    'Baby Karotten',
    'Cocktailtomate',
    'Ochsenherztomate',
    'gelbe Zucchini',
    'Patisson',
    'Spaghettikürbis',
    'Muskatkürbis',
    'Gartenkresse',
    'Löwenzahnsalat',
    'Portulak',
    'Batavia Salat',
    'Lollo Rosso',
    'Radicchio',
    'Sauerampfer',
    'Brennnessel',
    'Bärlauch',
    'Wildkräuter Mix',
    'Rhabarber Gemüse',

    // ===== Obst =====
    'Apfel',
    'roter Apfel',
    'grüner Apfel',
    'Banane',
    'Birne',
    'Orange',
    'Blutorange',
    'Zitrone',
    'Limette',
    'Grapefruit',
    'Mandarine',
    'Clementine',
    'Erdbeere',
    'Himbeere',
    'Blaubeere',
    'Heidelbeere',
    'Brombeere',
    'Johannisbeere',
    'rote Johannisbeere',
    'schwarze Johannisbeere',
    'Stachelbeere',
    'Traube',
    'rote Traube',
    'weiße Traube',
    'Pfirsich',
    'Nektarine',
    'Aprikose',
    'Pflaume',
    'Mirabelle',
    'Kirsche',
    'Sauerkirsche',
    'Ananas',
    'Mango',
    'Kiwi',
    'Melone',
    'Wassermelone',
    'Honigmelone',
    'Cantaloupe',
    'Papaya',
    'Passionsfrucht',
    'Maracuja',
    'Guave',
    'Litschi',
    'Feige',
    'Granatapfel',
    'Dattel',
    'Kokosnuss',
    'Avocado',
    'Quitte',
    'Rhabarber',
    'Physalis',
    'Kaki',
    'Sternfrucht',
    'Drachenfrucht',
    'Tamarinde',
    'Kumquat',
    'Preiselbeere',
    'Cranberry',
    'Holunderbeere',
    'Sanddornbeere',
    'Maulbeere',
    'Wildbeere Mix',
    'grüne Traube kernlos',
    'Weintraube blau',
    'Zwetschge',
    'Renekloden',
    'gelbe Kirsche',
    'Bio Apfel',
    'Boskop Apfel',
    'Granny Smith',
    'Williams Birne',
    'Nashi Birne',
    'Blutgrapefruit',
    'Bergamotte',
    'Yuzu',
    'Guanabana',
    'Rambutan',
    'Longan',
    'Jackfrucht',
    'Sternapfel',
    'Mangostane',

    // ===== Kräuter & Gewürze =====
    'Basilikum',
    'Oregano',
    'Thymian',
    'Rosmarin',
    'Petersilie',
    'glatte Petersilie',
    'krause Petersilie',
    'Dill',
    'Schnittlauch',
    'Minze',
    'Pfefferminze',
    'Koriander',
    'Kreuzkümmel',
    'Kümmel',
    'Paprikapulver',
    'edelsüßes Paprikapulver',
    'rosenscharf',
    'Zimt',
    'Muskatnuss',
    'Nelken',
    'Kurkuma',
    'Ingwerpulver',
    'schwarzer Pfeffer',
    'weißer Pfeffer',
    'grüner Pfeffer',
    'Kardamom',
    'Safran',
    'Lorbeerblatt',
    'Vanille',
    'Vanilleschote',
    'Senfkörner',
    'gelbe Senfkörner',
    'braune Senfkörner',
    'Fenchelsamen',
    'Anis',
    'Sternanis',
    'Chiliflocken',
    'Chilipulver',
    'Salbei',
    'Majoran',
    'Estragon',
    'Zitronengras',
    'Sumach',
    'Bockshornklee',
    'Wasabi',
    'Meerrettich',
    'Piment',
    'Lavendel',
    'Selleriesamen',
    'Sesam',
    'Schwarzkümmel',
    'Curry',
    'Curry Pulver',
    'Garlic Powder',
    'Zwiebelpulver',
    'Kakaopulver',
    'Liebstöckel',
    'Beifuß',
    'Kerbel',
    'Zitronenmelisse',
    'Ysop',
    'Wacholderbeeren',
    'Tonkabohne',
    'Galgant',
    'Kaffernlimettenblätter',
    'Currypulver mild',
    'Currypulver scharf',
    'Garam Masala',
    'Ras el Hanout',
    'Zaatar',
    'Harissa Gewürz',
    'geräuchertes Paprikapulver',
    'Cayennepfeffer',
    'rosa Pfeffer',
    'Szechuanpfeffer',
    'Vanillezucker',
    'Zimtstange',
    'ganze Nelken',
    'Muskatblüte',
    'Asafoetida',
    'Sesamöl geröstet',
    'Chili Öl',
    'Trüffelsalz',
    'Kräutersalz',
    'Steinsalz',

    // ===== Milchprodukte & Eier =====
    'Milch',
    'Vollmilch',
    'fettarme Milch',
    'Butter',
    'Sahne',
    'Schlagsahne',
    'Joghurt',
    'Naturjoghurt',
    'Griechischer Joghurt',
    'Käse',
    'Gouda',
    'Emmentaler',
    'Mozzarella',
    'Parmesan',
    'Cheddar',
    'Feta',
    'Ricotta',
    'Mascarpone',
    'Frischkäse',
    'Hüttenkäse',
    'Saure Sahne',
    'Schmand',
    'Crème fraîche',
    'Buttermilch',
    'Eier',
    'Eigelb',
    'Eiweiß',
    'Ghee',
    'Hafermilch',
    'Mandelmilch',
    'Sojamilch',
    'Kokosmilch',
    'Reismilch',
    'Kondensmilch',
    'Milchpulver',
    'Skyr',
    'Kefir',
    'Halloumi',
    'Burrata',
    'Provolone',
    'Gorgonzola',
    'Roquefort',
    'Brie',
    'Camembert',
    'Raclettekäse',
    'Bergkäse',
    'Tilsiter',
    'Ziegenkäse',
    'Schafskäse',
    'geriebener Käse',
    'Kochbutter',
    'Streichfett',
    'Margarine',
    'Vanillepudding',
    'Wachteleier',

    // ===== Fleisch, Fisch & Meeresfrüchte =====
    'Hähnchen',
    'Hähnchenbrust',
    'Hähnchenschenkel',
    'Hähnchenflügel',
    'Pute',
    'Rindfleisch',
    'Rinderhack',
    'Rindersteak',
    'Schweinefleisch',
    'Schweinebauch',
    'Schweinekotelett',
    'Lammfleisch',
    'Ente',
    'Kalbfleisch',
    'Speck',
    'Bacon',
    'Schinken',
    'Salami',
    'Bratwurst',
    'Wiener Würstchen',
    'Mett',
    'Hackfleisch',
    'Leber',

    'Fisch',
    'Lachs',
    'Thunfisch',
    'Kabeljau',
    'Seelachs',
    'Forelle',
    'Makrele',
    'Sardinen',
    'Hering',
    'Scholle',
    'Zander',
    'Hecht',

    'Garnelen',
    'Krabben',
    'Hummer',
    'Muscheln',
    'Miesmuscheln',
    'Tintenfisch',
    'Calamari',
    'Jakobsmuscheln',

    'Putenbrust',
    'Putenschnitzel',
    'Rinderfilet',
    'Rinderbraten',
    'Kalbsschnitzel',
    'Lammkeule',
    'Lammkotelett',
    'Gans',
    'Kaninchen',
    'Wildschwein',
    'Hirsch',
    'Rehfleisch',
    'Leberkäse',
    'Chorizo',
    'Cabanossi',
    'Kochschinken',
    'Rohschinken',
    'Speckwürfel',
    'Innereien',
    'Blutwurst',
    'Frankfurter Würstchen',
    'Seehecht',
    'Rotbarsch',
    'Wolfsbarsch',
    'Dorade',
    'Steinbutt',
    'Karpfen',
    'Aal',
    'Sushi Lachs',
    'Thunfisch Steak',
    'Fischstäbchen',
    'Räucherlachs',
    'Räucherforelle',
    'Austern',
    'Venusmuscheln',
    'Riesengarnelen',
    'Krabbenfleisch',
    'Surimi',
    'Kaviar',

    // ===== Vorrat / Basics =====
    'Reis',
    'Basmati Reis',
    'Jasminreis',
    'Naturreis',
    'Nudeln',
    'Spaghetti',
    'Penne',
    'Fusilli',
    'Lasagneplatten',
    'Mehl',
    'Weizenmehl',
    'Roggenmehl',
    'Dinkelmehl',
    'Maismehl',
    'Haferflocken',
    'Gerste',
    'Quinoa',
    'Couscous',
    'Bulgur',
    'Linsen',
    'rote Linsen',
    'grüne Linsen',
    'Kichererbsen',
    'Bohnen',
    'Kidneybohnen',
    'schwarze Bohnen',
    'weiße Bohnen',

    'Olivenöl',
    'Sonnenblumenöl',
    'Rapsöl',
    'Sesamöl',
    'Essig',
    'Apfelessig',
    'Weißweinessig',
    'Balsamico',
    'Sojasauce',
    'Honig',
    'Zucker',
    'brauner Zucker',
    'Puderzucker',
    'Salz',
    'Meersalz',

    'Backpulver',
    'Natron',
    'Hefe',
    'Trockenhefe',

    'Schokolade',
    'Zartbitterschokolade',
    'Vollmilchschokolade',
    'Kakaopulver',
    'Erdnussbutter',
    'Marmelade',
    'Nussmus',

    'Vollkornreis',
    'Risotto Reis',
    'Sushireis',
    'Wildreis',
    'Tagliatelle',
    'Rigatoni',
    'Farfalle',
    'Tortellini',
    'Ravioli',
    'Glasnudeln',
    'Reisnudeln',
    'Vollkornmehl',
    'Buchweizenmehl',
    'Kichererbsenmehl',
    'Panko',
    'Semmelbrösel',
    'Grieß',
    'Hirse',
    'Amaranth',
    'Chiasamen',
    'Leinsamen',
    'Kürbiskerne',
    'Sonnenblumenkerne',
    'Mandeln',
    'Walnüsse',
    'Haselnüsse',
    'Cashewkerne',
    'Pistazien',
    'Erdnüsse',
    'Pinienkerne',
    'Kokosraspeln',
    'Trockenfrüchte',
    'Rosinen',
    'getrocknete Aprikosen',
    'Datteln getrocknet',
    'Kokosöl',
    'Erdnussöl',
    'Traubenkernöl',
    'Leinöl',
    'Reisessig',
    'Sherryessig',
    'Worcestersauce',
    'Tomatenmark',
    'passierte Tomaten',
    'stückige Tomaten',
    'Kokosmilch Dose',
    'Gemüsebrühe',
    'Hühnerbrühe',
    'Rinderbrühe',
    'Fischfond',
    'Ahornsirup',
    'Agavendicksaft',
    'Reissirup',
    'brauner Rohrzucker',
    'Vanillinzucker',
    'Gelierzucker',
    'Speisestärke',
    'Kartoffelstärke',
    'Backkakao',
    'Kakaonibs',
    'Zartbitterkuvertüre',
    'weiße Schokolade',
  ];

  searchWord(search: string): string | undefined {
    if (search.length < 2) {
      return undefined;
    }
    const s = search.toLowerCase();
    return this.words.find((word) => {
      const w = word.toLowerCase();
      if (w.startsWith(s)) return true;
      return s.startsWith(w) && s.length - w.length <= 3;
    });
  }
}
